name: Deploy Web
on:
    push:
        branches: [slice-0/skeleton]
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with: { version: 8.15.0 }
            - run: pnpm install --frozen-lockfile
            - run: pnpm --filter web build
            - uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./apps/web/out
